name: Documentation

env:
 MERGE_REQUEST_ID: ${{github.event.number}}

on:
 push:
   branches:
     - master
 pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Print info
      run: |
        echo 'python/${MERGE_REQUEST_ID}'
