name: ScheduleTest

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  translation:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - name: Print
      run: echo "Hello scheduled test"
