name: ScheduleTest

on:
  push:
    branches: [master]
  schedule:
    - cron: '10 8 * * 1'

jobs:
  translation:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - name: Print
      run: echo "hello world"
