name: ScheduleTest

on:
  pull_request:
  schedule:
    - cron: "0 8 * * 1"

jobs:
  translation:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - name: Print
      run: echo "Hello scheduled test"
